### ISSUE TITLE
service_idごとに異なる設定値をリクエストごとに設定したい

### ISSUE THREAD

**Issue by maedana** [quipper/sbpayment.rb#111]
はじめまして。日本語でよさそうなので日本語で失礼します。現在関わっている案件でこちらのgemを採用しとても便利に使わせて頂いております。(SBペイメントの仕様が凄い複雑なのとエラーメッセージがわかりにくくて当初大変苦労しておりました...)
本題ですが、要件として1つのシステム内でmarchant_idが共通でservice_idが異なる複数施設でSBペイメントを利用することになっています。最近になって本番用の設定情報を受け取ったのですが、marchant_idが同じでもservice_idが異なる場合は以下の各値は異なっておりました。(開発中は勝手な思い込みでmarchant_idごとに固定値だと思っていました...)
```
basic_auth_user
basic_auth_password
cipher_code
cipher_iv
hashkey
```
実装を拝見しますと、service_idはrequest時に個別の値を設定することが可能ですが、上記については`Sbpayment.configure`で指定するsingletonなクラスの値を利用しており、リクエストごとに個別の値を設定出来るようにはなってないようでした。specでやっているようにリクエスト前に無理やり値を再設定することは出来ますが、pumaのマルチスレッド下においては同時アクセスがあると危ういので`Sbpayment.configure`での上記設定ををリクエスト時に上書き出来る仕組みがあるといいなと思いました。

performで引数を取れるようにして上記値の利用箇所を上書き出来るようにすればいけそうな気がしています。
手元でまずは実装してみてpullreqしてみようと思います。もし改修せずとも何かいい方法があれば教えて頂けると助かります。

**Comment by maedana** [comment]
修正してみました。まだpullreqは出しませんが、この状態で実案件で試してみます。現時点での差分は
https://github.com/quipper/sbpayment.rb/compare/master...maedana:master-config-by-request
で見れます。

`spec/vcr_cassettes/`配下を一旦削除して元々走っていたspecがそのまま走ることと、追加したspecが動くことまでは確認しています。ただ、今回の案件では暗号化をしないので、`cipher_code/cipher_iv`の関連するところは全く自信がないです...

**Comment by kachick** [comment]
https://github.com/quipper/sbpayment.rb/pull/15 この辺において突貫で 複数の service id 設定できるようにした気がします。が、多分ザル実装ですね・・・

>実装を拝見しますと、service_idはrequest時に個別の値を設定することが可能ですが、上記についてはSbpayment.configureで指定するsingletonなクラスの値を利用しており、リクエストごとに個別の値を設定出来るようにはなってないようでした。specでやっているようにリクエスト前に無理やり値を再設定することは出来ますが、pumaのマルチスレッド下においては同時アクセスがあると危ういのでSbpayment.configureでの上記設定ををリクエスト時に上書き出来る仕組みがあるといいなと思いました。

これずっと自分の中でも気になってました。 提起ありがとうございます！ 🙏

**Comment by wozaki** [comment]
@maedana 
弊社都合により 2021-10-08 に https://github.com/quipper/sbpayment.rb の公開を停止いたします。
今後の対応につきましては別途ご案内いたします。
急なご連絡になり大変申し訳ありません。
