### ISSUE TITLE
決済時に発生するエラー（トークンサービス）のエラーが定義されていない

### ISSUE THREAD

**Issue by zak1ck** [quipper/sbpayment.rb#64]
**決済時に発生するエラー（トークンサービス）** に該当する、コードが`T1`と`T2`が定義されていない

**Comment by zak1ck** [comment]
PR投げて良いのであれば投げます

**Comment by kachick** [comment]
はい、この辺アップデート出来てなくてすみません、いただけると助かります・・・！ 🙇 

@wozaki レビューはお願いできますか？ 🙏

**Comment by zak1ck** [comment]
修正を取り込んでもらったので、こちらのIssueは閉じさせてもらいます。  
ありがとうございました！

**Comment by wozaki** [comment]
@zak1ck 
gem更新したら再度連絡いたします!

**Comment by wozaki** [comment]
@zak1ck 
gemの更新完了しました！
https://rubygems.org/gems/sbpayment/versions/0.9.1

また何かありましたらご連絡お願いいたします 🙇
